title: Power Plan
actions:
  - !cmd:
      command: 'powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61'
  - !cmd:
      command: 'powercfg -setactive e9a42b02-d5df-448d-aa00-03f14749eb61'
  - !cmd:
      command: 'powercfg -change -standby-timeout-ac 0'
  - !cmd:
      command: 'powercfg -h off'