title: Security Setup
actions:
  - !cmd:
      command: 'powershell -NoProfile -Command "Enable-ComputerRestore -Drive \"C:\""'
  - !cmd:
      command: 'powershell -NoProfile -Command "Checkpoint-Computer -Description \"heyOS Yedek\" -RestorePointType \"MODIFY_SETTINGS\""'